# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.provision "shell", path: "setup.sh"

#  config.vm.provider "virtualbox" do |vb|
#    vb.gui = false
#    vb.memory = "1024"
#  end

  config.vm.synced_folder "../../XZES40-Transformer", "/xzes40"
  # If you fail to mount the above directory try running:
  # `vagrant plugin install vagrant-vbguest`
end
